version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.10"

# This section tells Sphinx where the documentation source is
sphinx:
  configuration: module_4/docs/source/conf.py

# This section tells pip where the requirements file is
python:
  install:
    - requirements: module_4/requirements.txt