version: 2

# Set the version of Python to use
build:
  os: ubuntu-22.04
  tools:
    python: "3.10"

# Tell Sphinx where your configuration file is located
sphinx:
  configuration: module_4/docs/source/conf.py

# Tell pip where to find your requirements file
python:
  install:
    - requirements: module_4/requirements.txt